apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: heartcellatlas
spec:
  virtualhost:
    fqdn: www.heartcellatlas.org
  routes:
    - match: /
      services:
        - name: heart-cell-atlas
          port: 80
    - match: /static
      services:
        - name: heart-cell-191210
          port: 80          
    - match: /heart-191210
      prefixRewrite: "/" 
      services:
        - name: heart-cell-191210
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: heartcellatlas-backend
spec:
  virtualhost:
    fqdn: heartcellatlas-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: heart-cell-atlas
          port: 80
    - match: /static
      services:
        - name: heart-cell-191210
          port: 80          
    - match: /heart-191210
      prefixRewrite: "/" 
      services:
        - name: heart-cell-191210
          port: 80
