apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: heartcellatlas
spec:
  virtualhost:
    fqdn: www.heartcellatlas.org
  routes:
    - match: /
      services:
        - name: heart-cell-atlas
          port: 80
    - match: /static
      services:
        - name: heart-cell-191210
          port: 80          
    - match: /heart-191210
      prefixRewrite: "/" 
      services:
        - name: heart-cell-191210
          port: 80
    - match: /mural-200107
      prefixRewrite: "/" 
      services:
        - name: heart-cell-mural-200107
          port: 80
    - match: /endothelial-200103
      prefixRewrite: "/" 
      services:
        - name: heart-cell-endothelial-200103
          port: 80
    - match: /immune-200108
      prefixRewrite: "/" 
      services:
        - name: heart-cell-immune-200108
          port: 80
    - match: /fibroblasts
      prefixRewrite: "/" 
      services:
        - name: heart-cell-fibroblasts
          port: 80
    - match: /cmc-sanger-200110
      prefixRewrite: "/" 
      services:
        - name: heart-cell-cmc-sanger-200110
          port: 80
    - match: /mesothelial-200109
      prefixRewrite: "/" 
      services:
        - name: heart-cell-mesothelial-200109
          port: 80
    - match: /cmc-male-200117
      prefixRewrite: "/" 
      services:
        - name: heart-cell-cmc-male-200117
          port: 80
    - match: /cmc-female-200117
      prefixRewrite: "/" 
      services:
        - name: heart-cell-cmc-female-200117
          port: 80
    - match: /stromal-200117
      prefixRewrite: "/" 
      services:
        - name: heart-cell-stromal-200117
          port: 80
    - match: /atrial-cmc-200120
      prefixRewrite: "/" 
      services:
        - name: heart-cell-atrial-cmc-200120
          port: 80
    - match: /myeloid
      prefixRewrite: "/" 
      services:
        - name: heart-cell-myeloid
          port: 80
    - match: /lymphoid
      prefixRewrite: "/" 
      services:
        - name: heart-cell-lymphoid
          port: 80
    - match: /vascular
      prefixRewrite: "/" 
      services:
        - name: heart-cell-vascular
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: heartcellatlas-backend
spec:
  virtualhost:
    fqdn: heartcellatlas-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: heart-cell-atlas
          port: 80
    - match: /static
      services:
        - name: heart-cell-191210
          port: 80          
    - match: /heart-191210
      prefixRewrite: "/" 
      services:
        - name: heart-cell-191210
          port: 80
    - match: /heart-191210
      prefixRewrite: "/" 
      services:
        - name: heart-cell-191210
          port: 80
    - match: /mural-200107
      prefixRewrite: "/" 
      services:
        - name: heart-cell-mural-200107
          port: 80
    - match: /endothelial-200103
      prefixRewrite: "/" 
      services:
        - name: heart-cell-endothelial-200103
          port: 80
    - match: /immune-200108
      prefixRewrite: "/" 
      services:
        - name: heart-cell-immune-200108
          port: 80
    - match: /fibroblasts
      prefixRewrite: "/" 
      services:
        - name: heart-cell-fibroblasts
          port: 80
    - match: /cmc-sanger-200110
      prefixRewrite: "/" 
      services:
        - name: heart-cell-cmc-sanger-200110
          port: 80
    - match: /mesothelial-200109
      prefixRewrite: "/" 
      services:
        - name: heart-cell-mesothelial-200109
          port: 80
    - match: /cmc-male-200117
      prefixRewrite: "/" 
      services:
        - name: heart-cell-cmc-male-200117
          port: 80
    - match: /cmc-female-200117
      prefixRewrite: "/" 
      services:
        - name: heart-cell-cmc-female-200117
          port: 80
    - match: /stromal-200117
      prefixRewrite: "/" 
      services:
        - name: heart-cell-stromal-200117
          port: 80
    - match: /atrial-cmc-200120
      prefixRewrite: "/" 
      services:
        - name: heart-cell-atrial-cmc-200120
          port: 80
    - match: /myeloid
      prefixRewrite: "/" 
      services:
        - name: heart-cell-myeloid
          port: 80
    - match: /lymphoid
      prefixRewrite: "/" 
      services:
        - name: heart-cell-lymphoid
          port: 80
    - match: /vascular
      prefixRewrite: "/" 
      services:
        - name: heart-cell-vascular
          port: 80