apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas
      labels:
        app: heart-cell-atlas
    spec:
      volumes:
        - name: indexfiles
          emptyDir: {}
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh", "-c", "cp -r /data/kubespray/sanger/sites/heartcellatlas/site/. /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
        volumeMounts:
          - name: indexfiles
            mountPath: /data
        resources:
          requests:
            memory: "128M"
            cpu: "0.1"
          limits:
            memory: "512M"
            cpu: "0.7"
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: alpine/git
        command: ['/bin/sh', '-c', 'git -C /data/kubespray pull || git clone https://github.com/cellgeni/kubespray /data/kubespray']
        volumeMounts:
          - name: indexfiles
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-global
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-global
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-global
      labels:
        app: heart-cell-atlas-global
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.12.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-global
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/HCA_Heart_ctl200210_website.h5ad", "-t", "Heart Global", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
          limits:
            memory: "20Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/HCA_Heart_ctl200210_website.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-atrial-cm
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-atrial-cm
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-atrial-cm
      labels:
        app: heart-cell-atlas-atrial-cm
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.12.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-atrial-cm
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/HCA_Heart_Atrial_CM_c200110_website.h5ad", "-t", "Heart Atrial Cardiomyocytes", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/HCA_Heart_Atrial_CM_c200110_website.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-ventricular-cm
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-ventricular-cm
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-ventricular-cm
      labels:
        app: heart-cell-atlas-ventricular-cm
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.12.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-ventricular-cm
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/HCA_Heart_Ventricular_CM_c200110_website.h5ad", "-t", "Heart Ventricular Cardiomyocytes", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "7Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/HCA_Heart_Ventricular_CM_c200110_website.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-fibroblasts
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-fibroblasts
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-fibroblasts
      labels:
        app: heart-cell-atlas-fibroblasts
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.12.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-fibroblasts
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/HCA_Heart_Fibroblasts_ml200110_website.h5ad", "-t", "Heart Fibroblasts", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/HCA_Heart_Fibroblasts_ml200110_website.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-vascular
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-vascular
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-vascular
      labels:
        app: heart-cell-atlas-vascular
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.12.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-vascular
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/HCA_Heart_Vascular_ml200110_website.h5ad", "-t", "Heart Vascular", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/HCA_Heart_Vascular_ml200110_website.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-myeloid
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-myeloid
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-myeloid
      labels:
        app: heart-cell-atlas-myeloid
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.12.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-myeloid
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/HCA_Heart_Myeloid_ctl200110_website.h5ad", "-t", "Heart Myeloid", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/HCA_Heart_Myeloid_ctl200110_website.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-lymphoid
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-lymphoid
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-lymphoid
      labels:
        app: heart-cell-atlas-lymphoid
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.12.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-lymphoid
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/HCA_Heart_Lymphoid_ctl200110_website.h5ad", "-t", "Heart Lymphoid", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/HCA_Heart_Lymphoid_ctl200110_website.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
