apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas
      labels:
        app: heart-cell-atlas
    spec:
      volumes:
        - name: indexfiles
          emptyDir: {}
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh", "-c", "cp -r /data/kubespray/sanger/sites/heartcellatlas/site/. /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
        volumeMounts:
          - name: indexfiles
            mountPath: /data
        resources:
          requests:
            memory: "128M"
            cpu: "0.1"
          limits:
            memory: "512M"
            cpu: "0.7"
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: alpine/git
        command: ['/bin/sh', '-c', 'git -C /data/kubespray pull || git clone https://github.com/cellgeni/kubespray /data/kubespray']
        volumeMounts:
          - name: indexfiles
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-global
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-global
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-global
      labels:
        app: heart-cell-atlas-global
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-global
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/global.h5ad --title 'Heart Global' --host '0.0.0.0' --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
          limits:
            memory: "20Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/global.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-atrial-cm
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-atrial-cm
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-atrial-cm
      labels:
        app: heart-cell-atlas-atrial-cm
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-atrial-cm
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/atrial.h5ad --title 'Heart Atrial Cardiomyocytes' --host '0.0.0.0' --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/atrial.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-ventricular-cm
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-ventricular-cm
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-ventricular-cm
      labels:
        app: heart-cell-atlas-ventricular-cm
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-ventricular-cm
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/ventricular.h5ad --title 'Heart Ventricular Cardiomyocytes' --host '0.0.0.0' --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "7Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/ventricular.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-fibroblasts
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-fibroblasts
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-fibroblasts
      labels:
        app: heart-cell-atlas-fibroblasts
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-fibroblasts
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/fibroblasts.h5ad --title 'Heart Fibroblasts' --host '0.0.0.0' --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/fibroblasts.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-vascular
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-vascular
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-vascular
      labels:
        app: heart-cell-atlas-vascular
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-vascular
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/vascular.h5ad --title 'Heart Vascular' --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/vascular.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-immune
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-immune
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-immune
      labels:
        app: heart-cell-atlas-immune
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-immune
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/immune.h5ad --title 'Heart Immune' --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/immune.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-neuronal
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-neuronal
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-neuronal
      labels:
        app: heart-cell-atlas-neuronal
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-neuronal
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/neuronal.h5ad --title 'Heart Neuronal' --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/neuronal.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-adipocytes
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-adipocytes
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-adipocytes
      labels:
        app: heart-cell-atlas-adipocytes
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-adipocytes
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/adipocytes.h5ad --title 'Heart Adipocytes' --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/adipocytes.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-skm
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-skm
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-skm
      labels:
        app: heart-cell-atlas-skm
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-skm
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/skm.h5ad --title 'Adult Skeletal Muscle' --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "6Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/skm.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-cell-atlas-velo
spec:
  selector:
    matchLabels:
      app: heart-cell-atlas-velo
  replicas: 1
  template:
    metadata: 
      name: heart-cell-atlas-velo
      labels:
        app: heart-cell-atlas-velo
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: heart-cell-atlas-cellxgene-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: heart-cell-atlas-velo
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/velo.h5ad --title 'RNA Velocity of vascular cells' --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://heartcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "10Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/heartcellatlas/data/velo.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
