apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heart-cell-atlas-cellxgene-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: "glusterfs"