apiVersion: v1
kind: Service
metadata:
  name: heart-cell-atlas
  labels:
    app: heart-cell-atlas
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: heart-cell-atlas
---
apiVersion: v1
kind: Service
metadata:
  name: heart-cell-191210
  labels:
    app: heart-cell-191210
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: heart-cell-191210
---
