apiVersion: v1
kind: Service
metadata:
  name: heart-cell-atlas
  labels:
    app: heart-cell-atlas
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: heart-cell-atlas
---
apiVersion: v1
kind: Service
metadata:
  name: heart-cell-endothelial
  labels:
    app: heart-cell-endothelial
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: heart-cell-endothelial
---
apiVersion: v1
kind: Service
metadata:
  name: heart-cell-stromal
  labels:
    app: heart-cell-stromal
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: heart-cell-stromal
---
apiVersion: v1
kind: Service
metadata:
  name: heart-cell-global-190527
  labels:
    app: heart-cell-global-190527
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: heart-cell-global-190527
---
apiVersion: v1
kind: Service
metadata:
  name: heart-cell-endothelial-only
  labels:
    app: heart-cell-endothelial-only
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: heart-cell-endothelial-only
---
apiVersion: v1
kind: Service
metadata:
  name: heart-cell-immune
  labels:
    app: heart-cell-immune
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: heart-cell-immune
---
apiVersion: v1
kind: Service
metadata:
  name: heart-cell-adipocytes
  labels:
    app: heart-cell-adipocytes
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: heart-cell-adipocytes
---

