apiVersion: v1
kind: Service
metadata:
  name: pan-immune
  labels:
    app: pan-immune
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: pan-immune
---
apiVersion: v1
kind: Service
metadata:
  name: pan-immune-global
  labels:
    app: pan-immune-global
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: pan-immune-global
---
apiVersion: v1
kind: Service
metadata:
  name: pan-immune-t-cells
  labels:
    app: pan-immune-t-cells
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: pan-immune-t-cells
---
apiVersion: v1
kind: Service
metadata:
  name: pan-immune-spleen
  labels:
    app: pan-immune-spleen
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: pan-immune-spleen
---
