apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter
  namespace: jpt
spec:
  virtualhost:
    fqdn: jupyter.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-backend
  namespace: jpt
spec:
  virtualhost:
    fqdn: jupyter-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-new
  namespace: jpt
spec:
  virtualhost:
    fqdn: jupyter-new.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-new-backend
  namespace: jpt
spec:
  virtualhost:
    fqdn: jupyter-new-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-large
  namespace: jptl
spec:
  virtualhost:
    fqdn: jupyter-large.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-large-backend
  namespace: jptl
spec:
  virtualhost:
    fqdn: jupyter-large-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-large-new
  namespace: jptl
spec:
  virtualhost:
    fqdn: jupyter-large-new.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-large-new-backend
  namespace: jptl
spec:
  virtualhost:
    fqdn: jupyter-large-new-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jup-test
  namespace: jptt
spec:
  virtualhost:
    fqdn: jupyter-test.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: isee
spec:
  virtualhost:
    fqdn: isee.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: isee
          port: 3838
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: isee-backend
spec:
  virtualhost:
    fqdn: isee-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: isee
          port: 3838
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: transcriptomics
spec:
  virtualhost:
    fqdn: spatial-transcriptomics-research.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: transcriptomics
          port: 8080
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: transcriptomics-backend
spec:
  virtualhost:
    fqdn: spatial-transcriptomics-research-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: transcriptomics
          port: 8080
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: asthma-backend
spec:
  virtualhost:
    fqdn: asthma-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: asthma
          port: 9001
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: asthma
spec:
  virtualhost:
    fqdn: asthma.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: asthma
          port: 9001
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: scfind-backend
spec:
  virtualhost:
    fqdn: scfind-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: scfind
          port: 9000
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: scfind
spec:
  virtualhost:
    fqdn: scfind.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: scfind
          port: 9000
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: websocket
  namespace: jptt
spec:
  virtualhost:
    fqdn: jupyter-test.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  virtualhost:
    fqdn: prometheus.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: prometheus-server
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: grafana
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: grafana-backend
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: grafana
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: nf-server
spec:
  virtualhost:
    fqdn: nf-server.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: nf-server
          port: 9005
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: nf-web
spec:
  virtualhost:
    fqdn: pipelines.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: nf-web
          port: 8000
