# apiVersion: contour.heptio.com/v1beta1
# kind: IngressRoute
# metadata:
#   name: jupyter
#   namespace: jpt
# spec:
#   virtualhost:
#     fqdn: jupyter.cellgeni.sanger.ac.uk
#   routes:
#     - match: /
#       enableWebsockets: true
#       services:
#         - name: proxy-public
#           port: 80
# ---
# apiVersion: contour.heptio.com/v1beta1
# kind: IngressRoute
# metadata:
#   name: jupyter-backend
#   namespace: jpt
# spec:
#   virtualhost:
#     fqdn: jupyter-backend.cellgeni.sanger.ac.uk
#   routes:
#     - match: /
#       enableWebsockets: true
#       services:
#         - name: proxy-public
#           port: 80
# ---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-large
  namespace: jptl
spec:
  virtualhost:
    fqdn: jupyter-large.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-large-backend
  namespace: jptl
spec:
  virtualhost:
    fqdn: jupyter-large-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-xl
  namespace: jptx
spec:
  virtualhost:
    fqdn: jupyter-xl.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-xl-proxy
  namespace: jptx
spec:
  virtualhost:
    fqdn: jupyter-xl-proxy.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-xl-backend
  namespace: jptx
spec:
  virtualhost:
    fqdn: jupyter-xl-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
# apiVersion: contour.heptio.com/v1beta1
# kind: IngressRoute
# metadata:
#   name: jupyter-large-new
#   namespace: jptl
# spec:
#   virtualhost:
#     fqdn: jupyter-large-new.cellgeni.sanger.ac.uk
#   routes:
#     - match: /
#       enableWebsockets: true
#       services:
#         - name: proxy-public
#           port: 80
# ---
# apiVersion: contour.heptio.com/v1beta1
# kind: IngressRoute
# metadata:
#   name: jupyter-large-new-backend
#   namespace: jptl
# spec:
#   virtualhost:
#     fqdn: jupyter-large-new-backend.cellgeni.sanger.ac.uk
#   routes:
#     - match: /
#       enableWebsockets: true
#       services:
#         - name: proxy-public
#           port: 80
# ---
# apiVersion: contour.heptio.com/v1beta1
# kind: IngressRoute
# metadata:
#   name: jup-test
#   namespace: jptt
# spec:
#   virtualhost:
#     fqdn: jupyter-test.cellgeni.sanger.ac.uk
#   routes:
#     - match: /
#       enableWebsockets: true
#       services:
#         - name: proxy-public
#           port: 80
# ---
# apiVersion: contour.heptio.com/v1beta1
# kind: IngressRoute
# metadata:
#   name: jup-test-backend
#   namespace: jptt
# spec:
#   virtualhost:
#     fqdn: jupyter-test-backend.cellgeni.sanger.ac.uk
#   routes:
#     - match: /
#       enableWebsockets: true
#       services:
#         - name: proxy-public
#           port: 80
# ---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: isee
spec:
  virtualhost:
    fqdn: isee.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: isee
          port: 3838
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: isee-backend
spec:
  virtualhost:
    fqdn: isee-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: isee
          port: 3838
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  virtualhost:
    fqdn: prometheus.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: prometheus-server
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: grafana
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: grafana-backend
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: grafana
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: grafana-proxy
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana-proxy.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: grafana
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: nf-server
spec:
  virtualhost:
    fqdn: nf-server.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: nf-server
          port: 9005
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: nf-web
spec:
  virtualhost:
    fqdn: pipelines.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: nf-web
          port: 8000
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-wsss
  namespace: wsss
spec:
  virtualhost:
    fqdn: wsss.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: jupyter-wsss-backend
  namespace: wsss
spec:
  virtualhost:
    fqdn: wsss-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: proxy-public
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: selftarget-backend
spec:
  virtualhost:
    fqdn: selftarget-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: predictor
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: selftarget
spec:
  virtualhost:
    fqdn: selftarget.cellgeni.sanger.ac.uk
  routes:
    - match: /
      enableWebsockets: true
      services:
        - name: predictor
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: easter-buddies-backend
spec:
  virtualhost:
    fqdn: easter-buddies-backend.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: easter-buddies
          port: 8005
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: easter-buddies
spec:
  virtualhost:
    fqdn: easter-buddies.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: easter-buddies
          port: 8005
# apiVersion: contour.heptio.com/v1beta1
# kind: IngressRoute
# metadata:
#   name: cytokines-test
#   annotations:
#     contour.heptio.com/ingress.class: contour
#     contour.heptio.com/request-timeout: 1000s
# spec:
#   virtualhost:
#     fqdn: cytokines-test.cellgeni.sanger.ac.uk
#   routes:
#     - match: /
#       enableWebsockets: true
#       services:
#         - name: cytokines-app
#           port: 80
#     # - match: /static
#     #   #enableWebsockets: true
#     #   services:
#     #     - name: cytokines-resting
#     #       port: 80
#     # - match: /simulated
#     #   prefixRewrite: "/" 
#     #   #enableWebsockets: true
#     #   services:
#     #     - name: cytokines-simulated
#     #       port: 80
#     # - match: /resting
#     #   prefixRewrite: "/" 
#     #   #enableWebsockets: true
#     #   services:
#     #     - name: cytokines-resting
#     #       port: 80

