apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: asthma-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: asthma.cellgeni.sanger.ac.uk
    http: &asthma
      paths:
      - path: /
        backend:
          serviceName: asthma
          servicePort: 9001
  - host: asthma-backend-nginx.cellgeni.sanger.ac.uk
    http: *asthma
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-nginx
  namespace: jpt
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 33000m
spec:
  rules:
  - host: jupyter.cellgeni.sanger.ac.uk
    http: &jupyter
      paths:
      - path: /
        backend:
          serviceName: proxy-public
          servicePort: 80
  - host: jupyter-backend-nginx.cellgeni.sanger.ac.uk
    http: *jupyter
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-large-nginx
  namespace: jptl
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100000m
spec:
  rules:
  - host: jupyter-large.cellgeni.sanger.ac.uk
    http: &jupyter-large
      paths:
      - path: /
        backend:
          serviceName: proxy-public
          servicePort: 80
  - host: jupyter-large-backend-nginx.cellgeni.sanger.ac.uk
    http: *jupyter-large
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-xl-nginx
  namespace: jptx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100000m
spec:
  rules:
  - host: jupyter-xl.cellgeni.sanger.ac.uk
    http: &jupyter-xl
      paths:
      - path: /
        backend:
          serviceName: proxy-public
          servicePort: 80
  - host: jupyter-xl-backend-nginx.cellgeni.sanger.ac.uk
    http: *jupyter-xl
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metabase-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100000m
spec:
  rules:
  - host: metabase.cellgeni.sanger.ac.uk
    http: &metabase
      paths:
      - path: /
        backend:
          serviceName: metabase
          servicePort: 3000
  - host: metabase-backend-nginx.cellgeni.sanger.ac.uk
    http: *metabase
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-wsss
  namespace: wsss
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100000m
spec:
  rules:
  - host: wsss.cellgeni.sanger.ac.uk
    http: &jupyter-wsss
      paths:
      - path: /
        backend:
          serviceName: proxy-public
          servicePort: 80
  - host: wsss-backend-nginx.cellgeni.sanger.ac.uk
    http: *jupyter-wsss
