apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heart-dev-cellxgene-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "glusterfs"