apiVersion: v1
kind: Service
metadata:
  name: imaging-tracker
  labels:
    app: imaging-tracker
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: imaging-tracker
  selector:
    app: imaging-tracker

