# Settings for the init image
init:
  image:
    repository: quay.io/ebigxa/galaxy-sc-tertiary
    tag: 1.0.0
    pullPolicy: IfNotPresent
  force_copy: "__config__,__galaxy-central__,__tools__,__welcome__"

image:
  repository: quay.io/ebigxa/galaxy-web-k8s
  tag: v18.05
  pullPolicy: IfNotPresent

admin:
  email: cellgeni-su@sanger.ac.uk
  password: galaxypass
  api_key: askdhaskjdhqwkdnqdq
  username: admin

galaxy_conf:
  brand: "HX Single Cell"
  admin_users: cellgeni-su@sanger.ac.uk
  allow_user_creation: true
  allow_user_deletion: true
  cleanup_job: never
  enable_beta_mulled_containers: true


job_conf:
  runners:
    enable_local: "true"
    enable_k8: "true"
  destinations:
    default: "docker_dispatch"
    # docker_default: "k8s_default"
    no_docker_default: "local_no_container"

service:
  name: galaxy-svc
  type: NodePort

ingress:
  enabled: true


postgresql:
  imageTag: "9.6.5_for_18.05"
  persistence:
    subPath: "postgres-tertiary"

persistence:
  #subPath: "galaxy-sc"
  existingClaim: "galaxy-pvc"
  minikube:
    enabled: false

proftpd:
  enabled: flase
  service:
    type: NodePort