apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-cell-atlas-cvid
spec:
  selector:
    matchLabels:
      app: single-cell-atlas-cvid
  replicas: 2
  template:
    metadata: 
      name: single-cell-atlas-cvid
      labels:
        app: single-cell-atlas-cvid
    spec:
      volumes:
        - name: indexfiles
          emptyDir: {}
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: single-cell-atlas-cvid
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh", "-c", "cp -r /data/kubespray/sanger/sites/single-cell-atlas-cvid/site/. /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
        volumeMounts:
          - name: indexfiles
            mountPath: /data
        resources:
          requests:
            memory: "128M"
            cpu: "0.1"
          limits:
            memory: "512M"
            cpu: "0.7"
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: alpine/git
        command: ['/bin/sh', '-c', 'git -C /data/kubespray pull || git clone https://github.com/cellgeni/kubespray /data/kubespray']
        volumeMounts:
          - name: indexfiles
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-cell-atlas-cvid-ss2
spec:
  selector:
    matchLabels:
      app: single-cell-atlas-cvid-ss2
  replicas: 1
  template:
    metadata: 
      name: single-cell-atlas-cvid-ss2
      labels:
        app: single-cell-atlas-cvid-ss2
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: single-cell-atlas-cvid-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: single-cell-atlas-cvid-ss2
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/adata_SS2_cellxgene.h5ad -t steady_state_B_cells_Smart-seq2 --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://www.cvidcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "256M"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/vento/CVID/adata_SS2_cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-cell-atlas-cvid-10x
spec:
  selector:
    matchLabels:
      app: single-cell-atlas-cvid-10x
  replicas: 1
  template:
    metadata: 
      name: single-cell-atlas-cvid-10x
      labels:
        app: single-cell-atlas-cvid-10x
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: single-cell-atlas-cvid-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: single-cell-atlas-cvid-10x
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/adata_10X_activation_cellxgene.h5ad -t activated_PBMC_10X --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://www.cvidcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/vento/CVID/adata_10X_activation_cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvid-revision-bcells
spec:
  selector:
    matchLabels:
      app: cvid-revision-bcells
  replicas: 1
  template:
    metadata: 
      name: cvid-revision-bcells
      labels:
        app: cvid-revision-bcells
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: single-cell-atlas-cvid-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: cvid-revision-bcells
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/adata_B_cells_cellxgene.h5ad -t 'CVID revision Bcells' --host 0.0.0.0 --port 5005 --disable-annotations --scripts https://www.cvidcellatlas.org/zxtm/piwik2.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "256M"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/vento/CVID/adata_B_cells_cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---