apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: single-cell-atlas-cvid-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500M
  storageClassName: "glusterfs"