kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: lifebit
  name: lifebit-ns
rules:
- apiGroups: ["*"]
  # resources: ["deployments", "replicasets", "pods", "pvc", "pv", "sc"]
  resources: ["*"]
  verbs: ["*"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lifebit-binding
  namespace: lifebit
subjects:
- kind: User
  name: lifebit
  apiGroup: ""
roleRef:
  kind: Role
  name: lifebit-ns
  apiGroup: ""
