apiVersion: apps/v1
kind: Deployment
metadata:
  name: hemocytes
spec:
  selector:
    matchLabels:
      app: hemocytes
  replicas: 1
  template:
    metadata: 
      name: hemocytes
      labels:
        app: hemocytes
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hemocytes-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.15.0
        imagePullPolicy: IfNotPresent
        name: hemocytes
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/hemocytes.h5ad", "-t", "Atlas of Anopheles hemocytes", "--host", "0.0.0.0", "--port", "5005", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/hemocytes/hemocytes-v3.h5ad', '-O', '/data/hemocytes.h5ad']
        volumeMounts:
          - name: data
            mountPath: /data
