apiVersion: v1
kind: Service
metadata:
  name: cvid-activation
  labels:
    app: cvid-activation
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: cvid-activation