apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-sn-integration-donor-11-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: "glusterfs"