apiVersion: apps/v1
kind: Deployment
metadata:
  name: kidney-cell-atlas
spec:
  selector:
    matchLabels:
      app: kidney-cell-atlas
  replicas: 1
  template:
    metadata: 
      name: kidney-cell-atlas
      labels:
        app: kidney-cell-atlas
    spec:
      volumes:
        - name: indexfiles
          emptyDir: {}
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: index-page
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh", "-c", "cp -r /data/kubespray/sanger/sites/kidneycellatlas/site/. /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
        volumeMounts:
          - name: indexfiles
            mountPath: /data
        resources:
          requests:
            memory: "128M"
            cpu: "0.1"
          limits:
            memory: "512M"
            cpu: "0.7"
      initContainers:
      - name: pull-data
        image: alpine/git
        command: ['/bin/sh', '-c', 'git -C /data/kubespray pull || git clone https://github.com/cellgeni/kubespray /data/kubespray']
        volumeMounts:
          - name: indexfiles
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mature-non-pt-parenchyma
spec:
  selector:
    matchLabels:
      app: mature-non-pt-parenchyma
  replicas: 1
  template:
    metadata: 
      name: mature-non-pt-parenchyma
      labels:
        app: mature-non-pt-parenchyma
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kidney-cell-atlas-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: mature-non-pt-parenchyma
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/Mature_non_PT_parenchyma_v2.1.h5ad", "--title", "Mature kidney non-PT parenchyma", "--host", "0.0.0.0", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '-N', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Mature_non_PT_parenchyma_v2.1.h5ad', '-P', '/data']
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mature-kidney-immune
spec:
  selector:
    matchLabels:
      app: mature-kidney-immune
  replicas: 1
  template:
    metadata: 
      name: mature-kidney-immune
      labels:
        app: mature-kidney-immune
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kidney-cell-atlas-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: mature-kidney-immune
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/Mature_Immune_v2.1.h5ad", "--title", "Mature kidney immune", "--host", "0.0.0.0", "--port", "5005", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '-N', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Mature_Immune_v2.1.h5ad', '-P', '/data']
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mature-kidney-global
spec:
  selector:
    matchLabels:
      app: mature-kidney-global
  replicas: 1
  template:
    metadata: 
      name: mature-kidney-global
      labels:
        app: mature-kidney-global
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kidney-cell-atlas-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: mature-kidney-global
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/Mature_Full_v2.1.h5ad", "--title", "Mature kidney global", "--host", "0.0.0.0", "--port", "5005", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '-N', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Mature_Full_v2.1.h5ad', '-P', '/data']
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-kidney-stroma
spec:
  selector:
    matchLabels:
      app: fetal-kidney-stroma
  replicas: 1
  template:
    metadata: 
      name: fetal-kidney-stroma
      labels:
        app: fetal-kidney-stroma
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kidney-cell-atlas-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: fetal-kidney-stroma
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/Fetal_stroma.h5ad", "--title", "Fetal kidney stroma", "--host", "0.0.0.0", "--port", "5005", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '-N', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Fetal_stroma.h5ad', '-P', '/data']
        volumeMounts:
          - name: data
            mountPath: /data        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-kidney-global
spec:
  selector:
    matchLabels:
      app: fetal-kidney-global
  replicas: 1
  template:
    metadata: 
      name: fetal-kidney-global
      labels:
        app: fetal-kidney-global
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kidney-cell-atlas-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: fetal-kidney-global
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/Fetal_full.h5ad", "--title", "Fetal kidney global", "--host", "0.0.0.0", "--port", "5005", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '-N', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Fetal_full.h5ad', '-P', '/data']
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-kidney-developing-nephron
spec:
  selector:
    matchLabels:
      app: fetal-kidney-developing-nephron
  replicas: 1
  template:
    metadata: 
      name: fetal-kidney-developing-nephron
      labels:
        app: fetal-kidney-developing-nephron
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kidney-cell-atlas-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: fetal-kidney-developing-nephron
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/Fetal_nephron.h5ad", "--title", "Fetal kidney developing nephron", "--host", "0.0.0.0", "--port", "5005", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '-N', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Fetal_nephron.h5ad', '-P', '/data']
        volumeMounts:
          - name: data
            mountPath: /data   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-kidney-immune
spec:
  selector:
    matchLabels:
      app: fetal-kidney-immune
  replicas: 1
  template:
    metadata: 
      name: fetal-kidney-immune
      labels:
        app: fetal-kidney-immune
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kidney-cell-atlas-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: fetal-kidney-immune
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/Fetal_immune.h5ad", "--title", "Fetal kidney immune", "--host", "0.0.0.0", "--port", "5005", "--disable-annotations"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        image: mwendler/wget
        command: ['wget', '-N', '--no-check-certificate', 'https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Fetal_immune.h5ad', '-P', '/data']
        volumeMounts:
          - name: data
            mountPath: /data