apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tissue-stability-cellxgene-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
  storageClassName: "glusterfs"