apiVersion: apps/v1
kind: Deployment
metadata:
  name: fadnuclei
spec:
  selector:
    matchLabels:
      app: fadnuclei
  replicas: 1
  template:
    metadata: 
      name: fadnuclei
      labels:
        app: fadnuclei
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fadnuclei-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.11.0
        imagePullPolicy: IfNotPresent
        name: fadnuclei
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/190926_single_nuc_AD.h5ad", "-t", "snRNAseq of human FAD cortex", "--host", "0.0.0.0", "--port", "5005"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/fadnuclei/190926_single_nuc_AD.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data