---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: schistosomula-cell-atlas-cellgeni
spec:
  virtualhost:
    fqdn: schistosomulacellatlas.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: schistosomula-cell-atlas
          port: 80
    - match: /view
      prefixRewrite: "/" 
      services:
        - name: schistosomula-cell-atlas-cxg
          port: 80
    - match: /static
      services:
        - name: schistosomula-cell-atlas-cxg
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: schistosomula-cell-atlas
spec:
  virtualhost:
    fqdn: www.schistosomulacellatlas.org
  routes:
    - match: /
      services:
        - name: schistosomula-cell-atlas
          port: 80
    - match: /view
      prefixRewrite: "/" 
      services:
        - name: schistosomula-cell-atlas-cxg
          port: 80
    - match: /static
      services:
        - name: schistosomula-cell-atlas-cxg
          port: 80
---