apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schistosomula-cell-atlas-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: "glusterfs"