apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reproductivecellatlas-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: "glusterfs"