apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity
spec:
  selector:
    matchLabels:
      app: oral-cavity
  replicas: 1
  template:
    metadata: 
      name: oral-cavity
      labels:
        app: oral-cavity
    spec:
      volumes:
        - name: indexfiles
          emptyDir: {}
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: oral-cavity
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh", "-c", "cp -r /data/kubespray/sanger/sites/oral-cavity/site/. /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
        volumeMounts:
          - name: indexfiles
            mountPath: /data
        resources:
          requests:
            memory: "128M"
            cpu: "0.1"
          limits:
            memory: "512M"
            cpu: "0.7"
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: alpine/git
        command: ['/bin/sh', '-c', 'git -C /data/kubespray pull || git clone https://github.com/cellgeni/kubespray /data/kubespray']
        volumeMounts:
          - name: indexfiles
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-human
spec:
  selector:
    matchLabels:
      app: oral-cavity-human
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-human
      labels:
        app: oral-cavity-human
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-human
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/pooled_human_gv_sg.processed.cellxgene.h5ad", "--title", "Oral Cavity Human", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/pooled_human_gv_sg.processed.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-mouse
spec:
  selector:
    matchLabels:
      app: oral-cavity-mouse
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-mouse
      labels:
        app: oral-cavity-mouse
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-mouse
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/pooled_mouse.processed.cellxgene.h5ad", "--title", "Oral Cavity Mouse", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/pooled_mouse.processed.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-human-gingival
spec:
  selector:
    matchLabels:
      app: oral-cavity-human-gingival
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-human-gingival
      labels:
        app: oral-cavity-human-gingival
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-human-gingival
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/human_gingival.processed_v4.cellxgene.h5ad", "--title", "Oral Cavity Human Gingival", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/human_gingival.processed_v4.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-human-salivary
spec:
  selector:
    matchLabels:
      app: oral-cavity-human-salivary
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-human-salivary
      labels:
        app: oral-cavity-human-salivary
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-human-salivary
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/human_salivary_gland.processed.cellxgene.h5ad", "--title", "Oral Cavity Human Salivary Gland", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "5Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/human_salivary_gland.processed.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-mouse-tongue
spec:
  selector:
    matchLabels:
      app: oral-cavity-mouse-tongue
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-mouse-tongue
      labels:
        app: oral-cavity-mouse-tongue
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-mouse-tongue
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/tabula_muris_tongue.processed.cellxgene.h5ad", "--title", "Mouse Tongue", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/tabula_muris_tongue.processed.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-mouse-buccal-mucosa
spec:
  selector:
    matchLabels:
      app: oral-cavity-mouse-buccal-mucosa
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-mouse-buccal-mucosa
      labels:
        app: oral-cavity-mouse-buccal-mucosa
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-mouse-buccal-mucosa
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/jones19.processed.cellxgene.h5ad", "--title", "Mouse Buccal Mucosa", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/jones19.processed.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-mouse-parotid-gland
spec:
  selector:
    matchLabels:
      app: oral-cavity-mouse-parotid-gland
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-mouse-parotid-gland
      labels:
        app: oral-cavity-mouse-parotid-gland
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-mouse-parotid-gland
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/song18_mouse_saliva_gland.processed.cellxgene.h5ad", "--title", "Mouse SG Parotid Gland", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/song18_mouse_saliva_gland.processed.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oral-cavity-mouse-submandibular-gland
spec:
  selector:
    matchLabels:
      app: oral-cavity-mouse-submandibular-gland
  replicas: 1
  template:
    metadata: 
      name: oral-cavity-mouse-submandibular-gland
      labels:
        app: oral-cavity-mouse-submandibular-gland
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oral-cavity-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.16.4
        imagePullPolicy: IfNotPresent
        name: oral-cavity-mouse-submandibular-gland
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["cellxgene", "launch", "/data/song18_mouse_saliva_gland.processed.cellxgene.h5ad", "--title", "Mouse SG Submandibular Gland", "--host", "0.0.0.0", "--port", "5005", "--annotations-dir", "/data/"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/oral-cavity/song18_mouse_saliva_gland.processed.cellxgene.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---