apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fetal-organoid-skin-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500M
  storageClassName: "glusterfs"