---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: ucl-covid19-airway
spec:
  virtualhost:
    fqdn: ucl-covid19-airway.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: ucl-covid19-airway
          port: 80
    # - match: /static
    #   services:
    #     - name: ucl-covid19-airway-data
    #       port: 80
    # - match: /data
    #   prefixRewrite: "/" 
    #   services:
    #     - name: ucl-covid19-airway-data
    #       port: 80
---