apiVersion: v1
kind: Service
metadata:
  name: ucl-covid19-airway
  labels:
    app: ucl-covid19-airway
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: ucl-covid19-airway
---
apiVersion: v1
kind: Service
metadata:
  name: ucl-covid19-airway-data
  labels:
    app: ucl-covid19-airway-data
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: ucl-covid19-airway-data
---
