apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maternal-fetal-interface-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: "glusterfs"