proxy:
    secretToken: c65b057a6ba96ee5562f4ea7d78f949d353908f52601c50c29223dd30166ccf1
auth:
  admin:
    users:
      - ak27
      - vk6
      - svd

auth:
  type: ldap
  ldap:
    server:
      address: ldap-ro.internal.sanger.ac.uk
    dn:
      templates:
        - 'uid={username},ou=people,dc=sanger,dc=ac,dc=uk'
ingress:
    enabled: true
    hosts:
     - jupyter.cellgeni.sanger.ac.uk
     - jupyter.cellgeni.internal.sanger.ac.uk

singleuser:
  memory:
    limit: 8G
    guarantee: 1G
  cpu:
    limit: 8
    guarantee: .5
  image:
    # name: quay.io/cellgeni/cellgeni-jupyter
    name: jupyter/scipy-notebook
    # tag: v0.1
    tag: 8ccdfc1da8d5
  # lifecycleHooks:
  #   postStart:
  #     exec:
  #       command: ["cp", "-a", "files/*", "."]
