proxy:
    secretToken: c65b057a6ba96ee5562f4ea7d78f949d353908f52601c50c29223dd30166ccf1
auth:
  admin:
    users:
      - ak27
      - vk6
      - svd
  type: ldap
  ldap:
    server:
      address: ldap-ro.internal.sanger.ac.uk
    dn:
      templates:
        - 'uid={username},ou=people,dc=sanger,dc=ac,dc=uk'
ingress:
    enabled: true
    hosts:
     - jupyter-large.cellgeni.sanger.ac.uk
cull:
  timeout: 129600
  
singleuser:
  defaultUrl: "/lab"
  storage:
    capacity: 120Gi
  memory:
    limit: 200G
    guarantee: 200G
  cpu:
    limit: 12
    guarantee: 8
  image:
    name: quay.io/cellgeni/cellgeni-jupyter
    tag: v0.2.8
  lifecycleHooks:
    postStart:
      exec:
        command: ["bash", "/poststart.sh"]
