---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: limb-dev
spec:
  virtualhost:
    fqdn: limb-dev.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: limb-dev
          port: 80
    - match: /static
      services:
        - name: limb-dev-hindlimb
          port: 80
    - match: /hindlimb
      prefixRewrite: "/" 
      services:
        - name: limb-dev-hindlimb
          port: 80
---