apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limb-dev-cellxgene-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "glusterfs"