apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biliarytree-cellxgene-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: "glusterfs"