apiVersion: v1
kind: Service
metadata:
  name: chondrocytes
  labels:
    app: chondrocytes
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: chondrocytes
---
apiVersion: v1
kind: Service
metadata:
  name: chondrocytes-limb-and-bone
  labels:
    app: chondrocytes-limb-and-bone
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: chondrocytes-limb-and-bone
---
apiVersion: v1
kind: Service
metadata:
  name: chondrocytes-sid-lawrence-bone-atlas
  labels:
    app: chondrocytes-sid-lawrence-bone-atlas
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: chondrocytes-sid-lawrence-bone-atlas
---
apiVersion: v1
kind: Service
metadata:
  name: chondrocytes-hongbo
  labels:
    app: chondrocytes-hongbo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: chondrocytes-hongbo
---
apiVersion: v1
kind: Service
metadata:
  name: chondrocytes-ucla-hindlimb
  labels:
    app: chondrocytes-ucla-hindlimb
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: chondrocytes-ucla-hindlimb
---
