
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-lung
spec:
  selector:
    matchLabels:
      app: fetal-lung
  replicas: 1
  template:
    metadata: 
      name: fetal-lung
      labels:
        app: fetal-lung
    spec:
      volumes:
        - name: indexfiles
          emptyDir: {}
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: fetal-lung
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh", "-c", "cp -r /data/kubespray/sanger/sites/fetal-lung/site/. /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
        volumeMounts:
          - name: indexfiles
            mountPath: /data
        resources:
          requests:
            memory: "128M"
            cpu: "0.1"
          limits:
            memory: "512M"
            cpu: "0.7"
      initContainers:
      - name: pull-data
        image: alpine/git
        command: ['/bin/sh', '-c', 'git -C /data/kubespray pull || git clone https://github.com/cellgeni/kubespray /data/kubespray']
        volumeMounts:
          - name: indexfiles
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-lung-main
spec:
  selector:
    matchLabels:
      app: fetal-lung-main
  replicas: 1
  template:
    metadata: 
      name: fetal-lung-main
      labels:
        app: fetal-lung-main
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fetal-lung-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.14.1
        imagePullPolicy: IfNotPresent
        name: fetal-lung
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/191204DaweiRNA.h5ad -t 'FetalLung (log-normalized)' --host 0.0.0.0 --port 5005 --about https://fetal-lung.cellgeni.sanger.ac.uk --scripts https://fetal-lung.cellgeni.sanger.ac.uk/piwik.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "6Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/fetal-lung/191204DaweiRNA.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-lung-rbc
spec:
  selector:
    matchLabels:
      app: fetal-lung-rbc
  replicas: 1
  template:
    metadata: 
      name: fetal-lung-rbc
      labels:
        app: fetal-lung-rbc
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fetal-lung-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.14.1
        imagePullPolicy: IfNotPresent
        name: fetal-lung-rbc
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/200222RBC.h5ad -t 'RBC' --host 0.0.0.0 --port 5005 --about https://fetal-lung.cellgeni.sanger.ac.uk --scripts https://fetal-lung.cellgeni.sanger.ac.uk/piwik.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/fetal-lung/200222RBC.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-lung-epi
spec:
  selector:
    matchLabels:
      app: fetal-lung-epi
  replicas: 1
  template:
    metadata: 
      name: fetal-lung-epi
      labels:
        app: fetal-lung-epi
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fetal-lung-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.14.1
        imagePullPolicy: IfNotPresent
        name: fetal-lung-epi
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/200226Epi.h5ad -t 'Epi' --host 0.0.0.0 --port 5005 --about https://fetal-lung.cellgeni.sanger.ac.uk --scripts https://fetal-lung.cellgeni.sanger.ac.uk/piwik.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/fetal-lung/200226Epi.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetal-lung-endo
spec:
  selector:
    matchLabels:
      app: fetal-lung-endo
  replicas: 1
  template:
    metadata: 
      name: fetal-lung-endo
      labels:
        app: fetal-lung-endo
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fetal-lung-pvc
      containers:
      - image: quay.io/cellgeni/cellxgene:0.14.1
        imagePullPolicy: IfNotPresent
        name: fetal-lung-endo
        ports:
        - containerPort: 5005
          name: cellxgene
        command: ["/bin/sh"]
        args: ["-c", "yes | cellxgene launch /data/200223Endo.h5ad -t 'Endo' --host 0.0.0.0 --port 5005 --about https://fetal-lung.cellgeni.sanger.ac.uk --scripts https://fetal-lung.cellgeni.sanger.ac.uk/piwik.js"]
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512M"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: 1
      initContainers:
      - name: pull-data
        imagePullPolicy: IfNotPresent
        image: garland/aws-cli-docker
        command: ['aws','--endpoint-url=https://cog.sanger.ac.uk', 's3', 'cp', 's3://cellgeni/fetal-lung/200223Endo.h5ad', '/data']
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
