apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: fetal-lung
spec:
  virtualhost:
    fqdn: fetal-lung.cellgeni.sanger.ac.uk
  routes:
    - match: /
      services:
        - name: fetal-lung
          port: 80
    - match: /static
      services:
        - name: fetal-lung-main
          port: 80
    - match: /main
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-main
          port: 80
    - match: /rbc
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-rbc
          port: 80
    - match: /endo
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-endo
          port: 80
    - match: /epi
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-epi
          port: 80
    - match: /fsm
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-fsm
          port: 80
    - match: /imm
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-imm
          port: 80
    - match: /cluster0
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster0
          port: 80
    - match: /cluster1
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster1
          port: 80
    - match: /cluster2
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster2
          port: 80
    - match: /cluster3
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster3
          port: 80
    - match: /cluster4
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster4
          port: 80
    - match: /cluster5
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster5
          port: 80
    - match: /cluster6
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster6
          port: 80
    - match: /cluster7
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster7
          port: 80
    - match: /cluster8
      prefixRewrite: "/" 
      services:
        - name: fetal-lung-cluster8
          port: 80
---