apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: developmentcellatlas-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: "glusterfs"