apiVersion: v1
kind: Service
metadata:
  name: placental-organoid-experiment
  labels:
    app: placental-organoid-experiment
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: placental-organoid-experiment
---
apiVersion: v1
kind: Service
metadata:
  name: placental-organoid-experiment-donors-1-and-2
  labels:
    app: placental-organoid-experiment-donors-1-and-2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: placental-organoid-experiment-donors-1-and-2
---
apiVersion: v1
kind: Service
metadata:
  name: placental-organoid-experiment-donor-1
  labels:
    app: placental-organoid-experiment-donor-1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: placental-organoid-experiment-donor-1
---
apiVersion: v1
kind: Service
metadata:
  name: placental-organoid-experiment-donor-2
  labels:
    app: placental-organoid-experiment-donor-2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: cellxgene
  selector:
    app: placental-organoid-experiment-donor-2
---